export const legalData = {
  terms: {
    en: {
      title: "Terms of Service",
      content: `Last updated: April 2026

1. Acceptance of Terms
By accessing or using SeedX ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.

2. Description of Service
SeedX is an AI-powered content generation tool that helps creators transform ideas into multi-platform content including Xiaohongshu posts, Chinese tweets, and English tweets.

3. User Accounts
You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activities that occur under your account.

4. Subscription and Payment
SeedX offers a free tier with limited usage and a Pro subscription. Payments are processed securely through Paddle. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel.

5. Cancellation
You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. You will retain access to Pro features until then.

6. Refund Policy
We offer a 7-day money-back guarantee. If you are not satisfied within 7 days of your initial purchase, contact us for a full refund. No refunds are issued after 7 days.

7. Acceptable Use
You agree not to use SeedX to:
- Generate illegal, harmful, or misleading content
- Violate any applicable laws or regulations
- Attempt to reverse engineer or copy the Service
- Use automated means to abuse the Service

8. Intellectual Property
SeedX and its original content, features, and functionality are owned by the SeedX team. Content generated by the AI belongs to the user who created it.

9. AI-Generated Content Disclaimer
SeedX uses AI to generate content. We do not guarantee the accuracy, originality, or fitness of generated content for any particular purpose. Users are solely responsible for reviewing and using generated content.

10. Limitation of Liability
To the maximum extent permitted by law, SeedX shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.

11. Changes to Terms
We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.

12. Contact
For any questions regarding these terms, contact us at:
jadelu0824@hotmail.com`
    },
    cn: {
      title: "服务条款",
      content: `最后更新：2026年4月

1. 接受条款
访问或使用 SeedX（以下简称「本服务」）即表示您同意受本服务条款的约束。如您不同意，请停止使用本服务。

2. 服务说明
SeedX 是一款 AI 驱动的内容生成工具，帮助创作者将想法转化为多平台内容，包括小红书笔记、中文推文及英文推文。

3. 用户账户
您有责任保管好账户凭据。您账户下发生的所有活动均由您负责。

4. 订阅与付款
SeedX 提供免费版（有限次数）及 Pro 订阅版本。付款通过 Paddle 安全处理。订阅即表示您授权我们按周期自动扣款，直至您取消订阅。

5. 取消订阅
您可随时取消订阅。取消将在当前计费周期结束后生效，您在此之前仍可使用 Pro 功能。

6. 退款政策
我们提供 7 天退款保障。若您在首次购买后 7 天内对服务不满意，可联系我们申请全额退款。7 天后不予退款。

7. 使用规范
您同意不使用 SeedX 进行以下行为：
- 生成违法、有害或误导性内容
- 违反任何适用法律法规
- 尝试对本服务进行逆向工程或复制
- 通过自动化手段滥用本服务

8. 知识产权
SeedX 及其原创内容、功能归 SeedX 团队所有。用户通过 AI 生成的内容归用户本人所有。

9. AI 生成内容免责声明
SeedX 使用 AI 生成内容。我们不保证生成内容的准确性、原创性或适用性。用户需自行审核并承担使用生成内容的全部责任。

10. 责任限制
在法律允许的最大范围内，SeedX 不对因使用本服务而产生的任何间接、附带或后果性损失承担责任。

11. 条款变更
我们保留随时修改本条款的权利。继续使用本服务即表示接受更新后的条款。

12. 联系方式
如有任何疑问，请联系：jadelu0824@hotmail.com`
    }
  },
  privacy: {
    en: {
      title: "Privacy Policy",
      content: `Last updated: April 2026

1. Introduction
SeedX ("we", "our", "us") is committed to protecting your privacy. This policy explains how we collect, use, and protect your information.

2. Information We Collect
- Account information: email address and name (when you join the waitlist or create an account)
- Usage data: content inputs, generation history, feature usage patterns
- Payment information: processed by Paddle; we do not store your payment card details
- Technical data: browser type, device information, IP address

3. How We Use Your Information
- To provide and improve the Service
- To send product updates and important notices
- To process payments and manage subscriptions
- To respond to your inquiries and support requests
- To analyze usage patterns and improve user experience

4. Data Storage
Your data is stored securely using Supabase. AI generation is powered by DeepSeek API. We do not store the content you generate beyond what is necessary to provide the Service.

5. Third-Party Services
We use the following third-party services:
- Supabase: database and authentication
- DeepSeek: AI content generation
- Paddle: payment processing
Each service has its own privacy policy governing their use of your data.

6. Data Sharing
We do not sell, trade, or rent your personal information to third parties. We may share data only when required by law or to protect our rights.

7. Cookies
We use essential cookies to maintain your session and preferences. We do not use advertising or tracking cookies.

8. Your Rights
You have the right to:
- Access the personal data we hold about you
- Request correction of inaccurate data
- Request deletion of your data
- Withdraw consent at any time

9. Data Retention
We retain your data for as long as your account is active or as needed to provide the Service. You may request deletion at any time by contacting us.

10. Children's Privacy
SeedX is not intended for users under the age of 13. We do not knowingly collect data from children.

11. Changes to This Policy
We may update this policy from time to time. We will notify you of significant changes via email.

12. Contact
For privacy-related inquiries: jadelu0824@hotmail.com`
    },
    cn: {
      title: "隐私政策",
      content: `最后更新：2026年4月

1. 简介
SeedX 重视您的隐私。本政策说明我们如何收集、使用和保护您的信息。

2. 收集的信息
- 账户信息：邮箱地址及姓名（加入 waitlist 或创建账户时）
- 使用数据：内容输入、生成记录、功能使用情况
- 支付信息：由 Paddle 处理，我们不存储您的银行卡信息
- 技术数据：浏览器类型、设备信息、IP 地址

3. 信息用途
- 提供并改进本服务
- 发送产品更新及重要通知
- 处理付款及管理订阅
- 回应您的咨询及支持请求
- 分析使用规律以改善用户体验

4. 数据存储
您的数据通过 Supabase 安全存储。AI 生成功能由 DeepSeek API 提供支持。我们不会在提供服务所需范围之外存储您生成的内容。

5. 第三方服务
我们使用以下第三方服务：
- Supabase：数据库与身份验证
- DeepSeek：AI 内容生成
- Paddle：支付处理
各服务均有其独立的隐私政策。

6. 数据共享
我们不会出售、交易或出租您的个人信息。仅在法律要求或保护我们权益时才会共享数据。

7. Cookie
我们使用必要的 Cookie 来维持您的会话和偏好设置。我们不使用广告或追踪 Cookie。

8. 您的权利
您有权：
- 访问我们持有的您的个人数据
- 请求更正不准确的数据
- 请求删除您的数据
- 随时撤回同意

9. 数据保留
我们在您的账户有效期间或提供服务所需期间保留您的数据。您可随时联系我们请求删除。

10. 儿童隐私
SeedX 不面向 13 岁以下用户。我们不会有意收集儿童数据。

11. 政策变更
我们可能定期更新本政策，重大变更将通过邮件通知您。

12. 联系方式
隐私相关问题请联系：jadelu0824@hotmail.com`
    }
  },
  refund: {
    en: {
      title: "Refund Policy",
      content: `Last updated: April 2026

1. 7-Day Money-Back Guarantee
We offer a full refund within 7 days of your initial purchase if you are not satisfied with SeedX Pro for any reason. No questions asked.

2. How to Request a Refund
To request a refund, email us at jadelu0824@hotmail.com with:
- The email address used for purchase
- Your reason for requesting a refund (optional)
We will process your refund within 5 business days.

3. Eligibility
- Refund requests must be made within 7 days of purchase
- Only first-time purchases are eligible for the money-back guarantee
- Refunds are not available for renewals or subsequent subscription periods

4. Subscription Cancellation
Canceling your subscription stops future charges but does not automatically trigger a refund. To request a refund, please contact us directly.

5. Processing Time
Refunds are typically processed within 5-10 business days depending on your payment provider.

6. Contact
For refund requests: jadelu0824@hotmail.com`
    },
    cn: {
      title: "退款政策",
      content: `最后更新：2026年4月

1. 7天无理由退款保障
若您在首次购买 SeedX Pro 后 7 天内因任何原因对服务不满意，可申请全额退款，无需说明理由。

2. 如何申请退款
请发送邮件至 jadelu0824@hotmail.com，注明：
- 购买时使用的邮箱地址
- 退款原因（选填）
我们将在 5 个工作日内处理您的退款申请。

3. 退款资格
- 退款申请须在购买后 7 天内提出
- 退款保障仅适用于首次购买
- 续费或后续订阅周期不适用退款保障

4. 取消订阅
取消订阅将停止后续扣款，但不会自动触发退款。如需退款，请直接联系我们。

5. 处理时间
退款通常在 5-10 个工作日内到账，具体时间取决于您的支付方式。

6. 联系方式
退款申请请联系：jadelu0824@hotmail.com`
    }
  }
};
